#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            0
bspc config window_gap              30

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback_color 	"#fae3b0"
bspc config active_border_color     "#ddb6f2"

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

feh --bg-fill ~/.software/catppuccinWallpapers/minimalistic/blue_unicat.png &
pidof polybar && pkill polybar
$HOME/.config/polybar/launch.sh &
pidof picom || pkill picom
picom -f --experimental-backends &
xsetroot -cursor_name left_ptr
# redshift -x & # reset color of screen
# redshift -O 3000 & # make it warmer!
setxkbmap -option "ctrl:swapcaps"
