#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            0
bspc config window_gap              15

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focused_border_color	"#81A1C1"
bspc config active_border_color     "#ECEFF4"
bspc config normal_border_color     "#B48EAD"
bspc config presel_feedback_color 	"#5E81AC"

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

feh --bg-scale ~/.software/wallpapers/Anime/anime-coffee-girl.jpg &
pidof polybar || pkill polybar
$HOME/.software/polybar-collection/themes/minimal/launch.sh &
pidof picom || pkill picom
picom -f --experimental-backends &
xsetroot -cursor_name left_ptr
setxkbmap -option "ctrl:swapcaps"
pidof dunst && pkill dunst
dunst &
